export const SessionState = {
  IDLE: "IDLE",
  WAITING_FOR_ACCEPT: "WAITING_FOR_ACCEPT",
  ESTABLISH_CONNECTION: "ESTABLISH_CONNECTION",
  IN_PROGRESS: "IN_PROGRESS",
  CLOSING_SESSION: "CLOSING_SESSION",
};
